"""empty message

Revision ID: 050c029b5108
Revises: bd77c6db0e1e
Create Date: 2016-10-21 23:16:50.200300

"""

# revision identifiers, used by Alembic.
revision = '050c029b5108'
down_revision = 'bd77c6db0e1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reservation', 'reserved', ['first_name'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    ### end Alembic commands ###
