"""empty message

Revision ID: b0e618ef5586
Revises: None
Create Date: 2016-11-02 18:54:33.417068

"""

# revision identifiers, used by Alembic.
revision = 'b0e618ef5586'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=80), nullable=True),
    sa.Column('ssn', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=35), nullable=True),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('job_title', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('live', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('room',
    sa.Column('room_num', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('book_from', sa.Date(), nullable=True),
    sa.Column('book_release', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('room_num')
    )
    op.create_table('search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_in', sa.Date(), nullable=True),
    sa.Column('date_out', sa.Date(), nullable=True),
    sa.Column('members', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('room_num', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('date_in', sa.Date(), nullable=True),
    sa.Column('date_out', sa.Date(), nullable=True),
    sa.Column('members', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('phone_num', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('check_in', sa.Boolean(), nullable=True),
    sa.Column('check_out', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_num'], ['room.room_num'], ),
    sa.PrimaryKeyConstraint('reservation_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('search')
    op.drop_table('room')
    op.drop_table('employee')
    ### end Alembic commands ###
