"""empty message

Revision ID: db84e13387cb
Revises: 470ebcca6be2
Create Date: 2016-10-20 21:32:07.295838

"""

# revision identifiers, used by Alembic.
revision = 'db84e13387cb'
down_revision = '470ebcca6be2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('DOB', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'DOB')
    ### end Alembic commands ###
